"""Compose generation for the native install engine (roadmap 6.2).

One job: turn a catalog entry plus an install identity into the exact text of
three compose files and the keys that belong in `.env`. Pure functions, no
subprocess and no daemon, so the output can be asserted byte for byte — which
matters more here than anywhere else in the engine, because the first thing
that reports a wrong compose file is a build three hours later.

The *content* is template data under `catalog/installers/<game>/native/`
(style-guide §3), never a Python conditional. This module owns the identity,
the substitution, the refusal of anything that cannot be safely spliced, and
the merge into `.env`.

Why three files, restated where the code is:

* `docker-compose.yml` — `name:`, services, container names, image refs, ALL
  ports, binds, volumes, depends_on, healthchecks.
* `docker-compose.override.yml` — runtime `AC_*` env and the `./modules`
  mount, nothing structural: it is auto-loaded and it is rewritten by whatever
  settings surface comes next, whose YAML writer keeps only what it
  understands.
* `docker-compose.build.yml` — `build:` blocks only, never auto-loaded, so a
  post-install `up` cannot start a multi-hour rebuild.

**`ports:` appears in exactly one of them.** Compose CONCATENATES `ports:`
across files: a port "overridden" in the override publishes a second binding
rather than replacing the first. `test_composegen.py` asserts the rendered
override and build files carry no `ports:` key at any depth, and that test is
the only thing standing between a future edit and a stack that binds 3724
twice.
"""

from __future__ import annotations

import hashlib
import os
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

from yulon import platform
from yulon.catalog.catalog import CatalogEntry
from yulon.log import get_logger

logger = get_logger(__name__)

BASE_FILE = "docker-compose.yml"
OVERRIDE_FILE = "docker-compose.override.yml"
BUILD_FILE = "docker-compose.build.yml"
DOTENV_FILE = ".env"

COMPOSE_FILES: tuple[str, ...] = (BASE_FILE, OVERRIDE_FILE, BUILD_FILE)
"""The `-f` set for every build, in order. See `docker.build_staged()`."""

GENERATED_MARKER = "# generated by Yu'lon"
"""First-line marker every generated file carries, and the whole of the rewrite rule.

`generate-compose` rewrites a file that begins with this and refuses to touch
one that does not. The incident it exists for is in `rust-prior-art.md` §1: a
state file dropped into a directory made the generator overwrite a real
server's compose file and orphan its character volumes. A marker means the
engine can only ever destroy its own work.
"""

INSTALL_ID_LENGTH = 8
"""Hex digits of the path hash that name an install. 8 is what `docker ps` can show.

A collision would give two installs one compose project — the bug this exists
to prevent — so the length is a real trade. 32 bits over the handful of
directories one person installs to is a birthday probability under 1e-8, and
the state file's own `install_id` check catches the pathological case at
install time rather than letting it run.
"""

DEFAULT_IMAGE_PREFIX = "yulon.local/ac-wotlk-"
"""Where images this machine BUILDS are named.

Deliberately not upstream's `acore/`: a build tags whatever the base file's
`image:` says, so reusing an upstream ref would clobber a pulled image and let
a later `docker compose pull` silently replace this playerbots build with
upstream's vanilla worldserver. The first component contains a dot, so Docker
reads it as a registry HOST and can never resolve it to somebody else's Docker
Hub repo — a stale-image mistake then fails loudly at pull time instead of
booting a plausible-looking wrong server.
"""

# Runtime env the generated override starts with. Two keys, both load-bearing:
# without the first the one-shot never creates the playerbots schema, and
# without the second the bots never log in.
#
# The Linux installer's own override also pins AC_AI_PLAYERBOT_MIN/MAX_RANDOM_
# BOTS to 500/500, and this comment used to argue at length that they should
# stay out. They did not stay out — the compose diff against the proven install
# (2026-08-24) found that a native install would otherwise take mod-playerbots'
# defaults and hand the same user a different world from the same button, and
# they now ship in `catalog.json`'s `install.native.world_env`. Corrected after
# a sweep found this text still arguing the opposite of what the code does.
#
# The argument was not wrong, only outranked, and the part still worth keeping
# is the cost: an env key SHADOWS the matching row in playerbots.conf, so a
# settings surface that edits that file will appear to do nothing until this
# key is removed. Nor is rewriting the env itself immediate — a container that
# is already running keeps the population it started with until it is
# RECREATED, so anything that changes this number is changing what the next
# `up` builds, not what the world outside the window is doing. That is why the
# numbers are DATA in `catalog.json` and not a constant here — a per-game value
# a person may want different, style-guide §3. What is still unmeasured is
# whether 500 bots fits the laptop this path's preflight exists for; the first
# live gate owes an RSS reading at that population, and until it has one the
# number is decided, not earned.
DEFAULT_WORLD_ENV: Mapping[str, str] = {
    "AC_PLAYERBOTS_UPDATES_ENABLE_DATABASES": "1",
    "AC_AI_PLAYERBOT_RANDOM_BOT_AUTOLOGIN": "1",
}
"""Settings that are structural rather than tunable: without them the stack is wrong, not merely
different. Anything a person might reasonably want a different value for belongs in
`catalog.json`'s `install.native.world_env` instead — the playerbot population started here and
was moved there after an adversarial review pointed out that a per-game number in a module
constant is exactly what style-guide §3 forbids, and that one machine's bot population is not a
default for every machine.

The environment differences the compose diff turned up and this deliberately does NOT carry —
`AC_CCACHE`, `CTYPE`, `CSCRIPTS`, `DATAPATH`, `USER_CONF_PATH` and the three empty
`AC_RESTARTER_*` — are build-time settings upstream's compose file keeps on the runtime services
too. The image's `entrypoint.sh` reads none of them: it uses `CONF_DIR`, `LOGS_DIR` and
`ACORE_COMPONENT`, and the image sets `ACORE_COMPONENT` itself. Checked in the image, not assumed.
"""

# Characters that cannot be spliced into the templates safely, whatever the
# escaping. A scalar here lands in TWO contexts at once — a bare YAML value
# (`MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-<pw>}`) and a quoted, semicolon-
# separated one (`"ac-database;3306;root;<pw>;acore_auth"`) — and compose's own
# interpolation runs on top of both after YAML has already unescaped them. `#`
# truncates at a comment, `}` ends the `:-` default early, `;` splits the
# database field list, `"`/`\` break the quoted string, `$` opens another
# interpolation, and a newline splices arbitrary YAML. No single escaping
# survives all six, so a bad value is REFUSED: this is an install-time option
# and the user can pick another password.
_UNSAFE_SCALAR_CHARS = frozenset("$\"\\;#{}\r\n\t'")


class ComposeGenError(RuntimeError):
    """A compose file could not be generated (message is user-readable)."""


def install_id(server_dir: Path, *, platform_id: Callable[[], str] = platform.detect) -> str:
    """Short, stable id for one install, derived from where it lives.

    SHA-256 of the ABSOLUTE path, first `INSTALL_ID_LENGTH` hex digits. Three
    normalisations, each because two spellings of one directory must not become
    two stacks: the path is made absolute, back-slashes become forward slashes,
    and a trailing separator is dropped. On Windows it is also lowercased,
    because NTFS is case-insensitive and `C:\\Games\\wow` and `c:\\games\\wow`
    are the same folder.

    This is the value the compose project name carries and the value the state
    file records, which is what makes a COPIED install directory refusable:
    the copy's path hashes differently from the `install_id` its state file
    carries, so a resume in it is refused instead of adopting the original's
    containers and volumes.
    """
    return hashlib.sha256(_identity_key(server_dir, platform_id).encode()).hexdigest()[
        :INSTALL_ID_LENGTH
    ]


def _identity_key(server_dir: Path, platform_id: Callable[[], str]) -> str:
    text = str(Path(os.path.abspath(server_dir))).replace("\\", "/")
    while len(text) > 1 and text.endswith("/"):
        text = text[:-1]
    return text.lower() if platform_id() == "windows" else text


def project_name(
    game_id: str, server_dir: Path, *, platform_id: Callable[[], str] = platform.detect
) -> str:
    """This install's compose project: `yulon-<game>-<install id>`.

    Written into the base file's `name:`, which retires the `.env` pin on the
    native path entirely — `docker.compose_project_name()` already reads `name:`
    out of the files, so a moved folder keeps working because the identity
    travels inside it.

    Per-install rather than per-game because compose keys named VOLUMES by
    project too: two installs of one game under one project name would share a
    database volume, and the second `up` would mount the first's characters.
    """
    return f"yulon-{_slug(game_id)}-{install_id(server_dir, platform_id=platform_id)}"


BUILT_SERVICES: tuple[str, ...] = (
    "worldserver",
    "authserver",
    "db-import",
    "client-data",
)
"""The image suffixes the build overlay produces, in the base file's spelling.

Kept beside the prefix and the tag because the three together are the only
description of what a finished build leaves behind, and `docker.images_built()`
now has to ask about them by name — see `built_image_refs()`.
"""


def built_image_refs(
    server_dir: Path, *, platform_id: Callable[[], str] = platform.detect
) -> tuple[str, ...]:
    """The image references this install's build produces, fully qualified.

    Needed because "has this been built?" cannot be asked of compose. Measured
    on yulon-ubuntu (Docker 29.1.3, Compose 2.40.3, 2026-08-24): after a
    successful `compose -f… build`, `compose images -q` returns **nothing** —
    both bare and with the same `-f` set — and only starts answering once
    containers exist (`compose create` is enough; `up` is not required). Compose
    enumerates the images of a project's CREATED CONTAINERS, not of its service
    definitions, exactly as `images_built()`'s docstring feared.

    That window — built, no containers yet — is the whole window a resume asks
    in, so the old question answered "not built" for every finished build and a
    resume re-ran the compile. Cheap in BuildKit cache terms and still wrong:
    the engine would have reported hours of work it did not need to do.
    """
    tag = image_tag(server_dir, platform_id=platform_id)
    return tuple(f"{DEFAULT_IMAGE_PREFIX}{name}:{tag}" for name in BUILT_SERVICES)


def image_tag(server_dir: Path, *, platform_id: Callable[[], str] = platform.detect) -> str:
    """Default tag for images built for this install, so two builds cannot overwrite each other."""
    return f"native-{install_id(server_dir, platform_id=platform_id)}"


def _slug(text: str) -> str:
    """Lowercase `[a-z0-9_-]`, so the project name is legal and readable in `docker ps`."""
    out: list[str] = []
    for char in text.lower():
        if char.isascii() and (char.isalnum() or char in "-_"):
            out.append(char)
        elif out and out[-1] != "-":
            out.append("-")
    return "".join(out).strip("-_") or "game"


@dataclass(frozen=True)
class ComposePlan:
    """The three files' text plus the `.env` keys this install needs on top of them.

    `dotenv` is **always empty as this module is called today**, and saying so
    is the point: `render()` has no caller that passes a per-install password,
    so every value it writes is the catalog's fixed one, which the base file's
    interpolation default has to carry anyway. A docstring here once promised
    that a non-default password "lands in `.env` rather than being baked into
    the file"; nothing implemented that, and a caller trusting it would have
    written a generated secret into `docker-compose.yml` in seven places
    (review, 2026-08-23).

    The field stays because the `.env` merge is real machinery
    (`write_dotenv()`) that `write_plan()` applies when this is non-empty — it
    is the seam a per-install password would arrive through, not a claim that
    one already does.
    """

    base: str
    override: str
    build: str
    dotenv: Mapping[str, str]


def container_user(platform_id: Callable[[], str] = platform.detect) -> str:
    """The `user:` line for the services that write to the bound-out env/dist.

    On Windows this is `user: "0:0"`, and it is not a convenience. Docker
    Desktop mounts a Windows drive into the WSL2 VM over 9p/drvfs with
    `uid=0;gid=0` and mode 0755; the images run as `acore` (uid 1000); so a
    container that must write `env/dist/etc` cannot, and `ac-db-import` fails
    with "cp: cannot create regular file ...: Permission denied" on files whose
    Windows ACLs give the user full control. Measured on a clean Windows 11 box
    (2026-08-25): the identical import exits 0 with this key and 1 without it.
    `DOCKER_USER=root`, which the image's own error text suggests, does nothing
    here - the generated compose sets no `user:` at all, so the image wins.

    Everywhere else this stays a comment, deliberately. On Linux, running as
    root makes every file the container creates root-owned ON THE HOST, which
    breaks the reason `env/dist/etc` is bound out in the first place: the module
    system and the user edit those files. Windows pays no such price because 9p
    maps ownership back to the Windows account regardless of the writing uid.
    """
    if platform_id() == "windows":
        return 'user: "0:0"'
    return "# user: left to the image (acore) - see composegen.container_user()"


def render(
    entry: CatalogEntry,
    server_dir: Path,
    *,
    templates_root: Path,
    world_env: Mapping[str, str] | None = None,
    db_password: str | None = None,
    platform_id: Callable[[], str] = platform.detect,
) -> ComposePlan:
    """Render this entry's three compose files for an install in `server_dir`.

    `db_password` overrides the catalog's fixed password (for a game that
    generates one per install). **Whatever it is, it is rendered into
    `docker-compose.yml`** — as the `${DB_ROOT_PASSWORD:-…}` interpolation
    default, in seven places. The returned plan's `dotenv` is empty; see
    `ComposePlan.dotenv` for why that is stated rather than fixed.

    Raises:
        ComposeGenError: the entry has no `install.native` block, a template is
            missing, a placeholder was left unfilled, or a value cannot be
            safely spliced into YAML.
    """
    native = entry.install.native
    if native is None:
        raise ComposeGenError(
            f"{entry.name} does not say how to install natively (no `install.native` in "
            "catalog.json), so no compose files were generated."
        )
    templates = templates_root / native.templates
    password = db_password if db_password is not None else (entry.install.password.value or "")
    if not password:
        raise ComposeGenError(
            f"{entry.name} has no database root password to write into its compose files."
        )
    _refuse_unsafe(password, "the database root password")
    tag = image_tag(server_dir, platform_id=platform_id)
    project = project_name(entry.id, server_dir, platform_id=platform_id)
    # The entry's own settings layered over the structural defaults, and an
    # explicit `world_env` overriding both — that is the seam a settings
    # surface arrives through.
    env = dict(world_env) if world_env is not None else {**DEFAULT_WORLD_ENV, **native.world_env}
    base = _fill(
        _read_template(templates / "base.yml.tmpl"),
        {
            "PROJECT_NAME": project,
            "DB_PORT": str(entry.ports.db or 3306),
            "AUTH_PORT": str(entry.ports.auth),
            "WORLD_PORT": str(entry.ports.world),
            "SOAP_PORT": str(native.soap_port),
            "DB_PASSWORD": password,
            "IMAGE_PREFIX": DEFAULT_IMAGE_PREFIX,
            "IMAGE_TAG": tag,
            "CONTAINER_USER": container_user(platform_id),
        },
    )
    override = _fill(
        _read_template(templates / "override.yml.tmpl"), {"ENVIRONMENT": _env_block(env)}
    )
    build = _fill(
        _read_template(templates / "build.yml.tmpl"),
        # `.` and not the absolute path: the server dir IS the checkout, and
        # compose resolves a relative context against the file's own directory,
        # so a moved folder keeps building.
        {"BUILD_CONTEXT": "."},
    )
    return ComposePlan(base, override, build, {})


def _read_template(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ComposeGenError(f"the compose template {path} could not be read: {exc}") from exc


def _fill(template: str, values: Mapping[str, str]) -> str:
    """`{{TOKEN}}` substitution where an unresolved token is an ERROR.

    A template edit that adds a placeholder nobody fills would otherwise ship a
    compose file containing a literal `{{...}}`, which compose accepts happily
    as a string and which fails somewhere else entirely.
    """
    out = template
    for key, value in values.items():
        out = out.replace("{{" + key + "}}", value)
    start = out.find("{{")
    if start >= 0:
        raise ComposeGenError(f"unfilled compose placeholder near: {out[start:start + 40]!r}")
    return out


def _env_block(env: Mapping[str, str]) -> str:
    """The override's `environment:` mapping, indented to sit under it.

    Values are double-quoted strings without exception. AzerothCore reads these
    as text, and YAML would otherwise turn `1` into an int and `on` into a
    boolean — a distinction compose passes through to the container as
    `AC_..=true`, which no `.conf` parser expects.
    """
    lines: list[str] = []
    for key in sorted(env):
        if not _is_env_identifier(key):
            raise ComposeGenError(f"{key!r} is not a usable environment variable name")
        _refuse_unsafe(env[key], f"the value of {key}")
        lines.append(f'      {key}: "{env[key]}"')
    return "\n".join(lines)


def _is_env_identifier(key: str) -> bool:
    return (
        bool(key)
        and (key[0].isalpha() or key[0] == "_")
        and all(char.isalnum() or char == "_" for char in key)
    )


def _refuse_unsafe(value: str, what: str) -> None:
    bad = sorted(set(value) & _UNSAFE_SCALAR_CHARS)
    if bad:
        raise ComposeGenError(
            f"{what} contains {' '.join(repr(char) for char in bad)}, which cannot be written "
            "into a compose file safely. Use letters, digits and simple punctuation."
        )


def is_ours(path: Path) -> bool:
    """Did this engine write the file at `path`? Missing counts as ours to write.

    The whole of the rewrite rule (see `GENERATED_MARKER`): only the first line
    is consulted, because that is the one place a marker cannot be introduced
    by accident, and an unreadable file answers False — the fail-closed answer
    for "should I overwrite this".
    """
    if not path.exists():
        return True
    try:
        with path.open(encoding="utf-8", errors="replace") as fh:
            return fh.readline().startswith(GENERATED_MARKER)
    except OSError as exc:
        logger.warning(f"could not read {path} to see whether it is ours: {exc}")
        return False


def write_plan(
    plan: ComposePlan, server_dir: Path, *, replaceable: Sequence[str] = ()
) -> tuple[Path, ...]:
    """Write the three files (and merge `.env`), refusing to overwrite foreign ones.

    Returns the paths written, which is deliberately not always all three: a
    file whose content already matches is left alone so its mtime does not
    move, and an unchanged compose file is what tells a user's own `docker
    compose` that nothing needs recreating.

    `replaceable` names files the CALLER has separately proved may be
    overwritten despite carrying no marker, and it exists for exactly one file:
    `docker-compose.yml`, which the emulator repository ships at its own root.
    The server directory IS that checkout, so on every single install the clone
    stage lays an unmarked `docker-compose.yml` down before this runs, and the
    marker rule alone refused every install with "point the install at an empty
    folder" — told to a user who did, after a 2.4 GB clone (review,
    2026-08-23). This module cannot tell upstream's file from a real server's,
    so it does not guess; `native._generate_compose()` asks git whether the
    file is the tracked, unmodified one the clone wrote and passes the answer
    in. Nothing is replaceable by default.

    Raises:
        ComposeGenError: a compose file exists that this engine did not write
            and the caller did not name. Never deleted, never overwritten — the
            install stops instead, since the alternative is orphaning somebody's
            character volumes.
    """
    written: list[Path] = []
    for name, text in (
        (BASE_FILE, plan.base),
        (OVERRIDE_FILE, plan.override),
        (BUILD_FILE, plan.build),
    ):
        path = server_dir / name
        if name not in replaceable and not is_ours(path):
            raise ComposeGenError(
                f"{path} was not written by Yu'lon, so it was not touched and nothing was "
                "installed. Point the install at an empty folder, or move that file aside."
            )
        if path.exists() and path.read_text(encoding="utf-8") == text:
            continue
        path.write_text(text, encoding="utf-8", newline="\n")
        written.append(path)
    if plan.dotenv:
        written.append(write_dotenv(server_dir, plan.dotenv))
    return tuple(written)


def merge_dotenv(existing: str, additions: Mapping[str, str]) -> str:
    """`.env` text with `additions` applied: existing assignments replaced, new ones appended.

    No non-test caller reaches this today — `render()` returns an empty
    `dotenv`, so `write_plan()`'s branch never fires. It is written and tested
    ahead of the first caller that needs it (a per-install database password,
    or the settings surface writing a port binding), not because something
    already merges an `.env`.

    A merge and not a rewrite, because this file is shared. Compose interpolates
    the compose files from it, a later SOAP setup writes its own port binding
    into it, and the port-conflict remedy appends a `DOCKER_DB_EXTERNAL_PORT`
    — dropping a key nobody here recognises would silently undo one of those.

    An assignment is replaced in place so its position (and therefore which
    wins, since compose takes the LAST) does not change.
    """
    lines = existing.splitlines()
    remaining = dict(additions)
    for index, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("export "):
            stripped = stripped[len("export ") :].lstrip()
        key = stripped.split("=", 1)[0].strip() if "=" in stripped else ""
        if key in remaining:
            lines[index] = f"{key}={remaining.pop(key)}"
    if remaining:
        if lines and lines[-1].strip():
            lines.append("")
        lines.append("# Written by Yu'lon's install engine.")
        lines += [f"{key}={remaining[key]}" for key in sorted(remaining)]
    return "\n".join(lines) + "\n"


def write_dotenv(server_dir: Path, additions: Mapping[str, str]) -> Path:
    """Merge `additions` into `<server_dir>/.env`, atomically.

    Atomic and byte-preserving for the reason `docker.pin_project_name()` gives
    at length: this file can hold the database root password, and a truncating
    write interrupted by a full disk leaves a `.env` the user's database is no
    longer reachable through.
    """
    path = server_dir / DOTENV_FILE
    existing = path.read_text(encoding="utf-8", errors="replace") if path.is_file() else ""
    merged = merge_dotenv(existing, additions)
    tmp = path.with_name(path.name + ".yulon-new")
    try:
        tmp.write_text(merged, encoding="utf-8", newline="\n")
        os.replace(tmp, path)  # atomic on POSIX and on Windows
    except OSError:
        tmp.unlink(missing_ok=True)
        raise
    return path
