"""Tests for `yulon.catalog.families.dockerfile`: the marker on every render, and the
three answers `write()` can give about a file already in the way.

Pure: a `tmp_path` tree stands in for the template folder and the server dir, and the
three shipped template pairs are read straight off disk. No daemon.

Two things here are about bytes rather than behaviour, and both are real defects this
project can ship silently:

* the marker must appear ONCE. The shipped templates already open with it (G.6 asserts
  the filled text starts with `composegen.GENERATED_MARKER`), so a `render()` that
  prepends unconditionally stacks a second copy on every generated Dockerfile.
* the files must be written LF. The templates are LF in the index and CRLF in a Windows
  worktree under `core.autocrlf=true`, so a render on Windows that copied the worktree's
  endings — or a skip that accepted a CRLF file already on disk — would hand `docker
  build` a CRLF Dockerfile.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

import pytest

from yulon import resources
from yulon.catalog import composegen, native
from yulon.catalog.catalog import CatalogEntry, load_catalog
from yulon.catalog.families import dockerfile

TOKENS = {"CORE_DIR": "/opt/mangos", "MAKE_JOBS": "2", "CLIENT_BUILD": "8606"}
"""`CLIENT_BUILD` is deliberately unused by the stand-in templates: `fill()` refuses an
UNFILLED token and is indifferent to an unused one, and `entry_tokens()` hands the same
wider mapping to every template."""

TEMPLATES = resources.installers_dir()
CMANGOS_ENTRIES = [load_catalog().get(game) for game in ("wow-tbc", "wow-vanilla", "wow-tortoise")]

DOCKERFILE_BODY = (
    "FROM debian:12\nRUN cmake -DCMAKE_INSTALL_PREFIX={{CORE_DIR}} /src\nRUN make -j{{MAKE_JOBS}}\n"
)
IGNORE_BODY = "# the context for {{CORE_DIR}}\n*\n!src/core\nsrc/core/.git\n"
"""A token inside a comment: `fill()` refuses an unfilled one wherever it stands, and the
`.dockerignore` half goes through the same substitution as the Dockerfile."""


def templates(root: Path) -> Path:
    """A template pair carrying NO marker of its own — the prepend path."""
    folder = root / "native"
    folder.mkdir(parents=True)
    (folder / "Dockerfile.tmpl").write_text(DOCKERFILE_BODY, encoding="utf-8", newline="\n")
    (folder / "dockerignore.tmpl").write_text(IGNORE_BODY, encoding="utf-8", newline="\n")
    return folder


def shipped(entry: CatalogEntry) -> Path:
    """The real `catalog/installers/<game>/native` folder for a CMaNGOS entry."""
    native = entry.install.native
    assert native is not None and native.dockerfile_dir is not None
    return TEMPLATES / str(native.dockerfile_dir)


def server_dir(root: Path) -> Path:
    folder = root / "server"
    folder.mkdir()
    return folder


# -- render -------------------------------------------------------------------


def test_render_fills_tokens_and_starts_both_files_with_the_marker(tmp_path: Path) -> None:
    text, ignore = dockerfile.render(templates(tmp_path), TOKENS)
    assert text.startswith(composegen.GENERATED_MARKER + "\n")
    assert ignore.startswith(composegen.GENERATED_MARKER + "\n")
    assert "-DCMAKE_INSTALL_PREFIX=/opt/mangos /src" in text and "make -j2" in text
    assert "{{" not in text and "{{" not in ignore
    assert "# the context for /opt/mangos\n" in ignore, "both halves fill from the same tokens"
    assert "!src/core\n" in ignore


@pytest.mark.parametrize("entry", CMANGOS_ENTRIES, ids=lambda e: e.id)
def test_render_does_not_stack_a_second_marker_on_a_template_that_has_one(
    entry: CatalogEntry,
) -> None:
    """The shipped templates open with the marker line themselves (style-guide §3: the
    text is data). A `render()` that prepends unconditionally would put

        # generated by Yu'lon
        # generated by Yu'lon - do not hand-edit; the install engine rewrites this file.

    at the top of every generated Dockerfile — the plan's own draft did exactly that. The
    guarantee is "the marker is there", not "the marker is added".
    """
    text, ignore = dockerfile.render(shipped(entry), composegen.entry_tokens(entry))
    for name, rendered in ((dockerfile.DOCKERFILE, text), (dockerfile.DOCKERIGNORE, ignore)):
        assert rendered.startswith(composegen.GENERATED_MARKER), name
        assert rendered.count(composegen.GENERATED_MARKER) == 1, name
        assert rendered.splitlines()[0].startswith(composegen.GENERATED_MARKER + " "), name
    assert "{{" not in text and "{{" not in ignore
    assert f"CMAKE_INSTALL_PREFIX={composegen.entry_tokens(entry)['CORE_DIR']}" in text


@pytest.mark.parametrize("entry", CMANGOS_ENTRIES, ids=lambda e: e.id)
def test_render_of_a_shipped_template_carries_no_carriage_return(entry: CatalogEntry) -> None:
    """The worktree copy is CRLF under `core.autocrlf=true`; the render is not."""
    text, ignore = dockerfile.render(shipped(entry), composegen.entry_tokens(entry))
    assert "\r" not in text and "\r" not in ignore


def test_render_normalises_a_crlf_template_to_lf(tmp_path: Path) -> None:
    folder = templates(tmp_path)
    (folder / "Dockerfile.tmpl").write_bytes(DOCKERFILE_BODY.replace("\n", "\r\n").encode())
    text, _ = dockerfile.render(folder, TOKENS)
    assert "\r" not in text
    assert "RUN make -j2\n" in text


def test_render_refuses_an_unknown_token(tmp_path: Path) -> None:
    folder = templates(tmp_path)
    (folder / "Dockerfile.tmpl").write_text("FROM x\nRUN {{NOT_A_TOKEN}}\n", encoding="utf-8")
    with pytest.raises(dockerfile.DockerfileError, match="NOT_A_TOKEN"):
        dockerfile.render(folder, TOKENS)


# -- render: the secret may not reach a generated file ------------------------

SECRET = "tbc-0123456789abcdef"
"""Shaped like the real one: `<password.prefix><hex>`, as `.db_password` holds it and as
`CmangosInstaller._tokens()` carries it into the mapping K.4 hands `render()` whole."""


def test_render_refuses_a_dockerfile_template_that_names_the_password_token(
    tmp_path: Path,
) -> None:
    """The decision `composegen.generate()` took for the compose files, taken here too.

    A compose file holding the secret is a file the user owns: delete it, rotate, done. A
    Dockerfile holding it is baked into a content-addressed image layer, so `docker
    history` prints it long after the file is gone and undoing it means hunting every
    image built from that layer. So this is refused BY NAME, the way `generate()` refuses
    it, rather than being left to `fill()` — which minds an unfilled placeholder and has
    no opinion at all about a spelled one.

    The mapping deliberately CARRIES `DB_PASSWORD`: that is the shape K.4 hands over, and
    it is what makes this fixture violate exactly one rule. Without the key the template
    would fail as merely unfilled and the test would prove nothing about the refusal.
    """
    folder = templates(tmp_path)
    (folder / "Dockerfile.tmpl").write_text(
        "FROM debian:12\nENV DB_PASSWORD={{DB_PASSWORD}}\n", encoding="utf-8", newline="\n"
    )
    with pytest.raises(
        dockerfile.DockerfileError, match=r"DB_PASSWORD.*Dockerfile\.tmpl"
    ) as caught:
        dockerfile.render(folder, {**TOKENS, "DB_PASSWORD": SECRET})
    assert "docker history" in str(caught.value), "the refusal's own words, not fill()'s"
    assert SECRET not in str(caught.value), "a refusal about a secret does not print it"


def test_render_refuses_a_dockerignore_template_that_names_the_password_token(
    tmp_path: Path,
) -> None:
    """Both halves fill from the same mapping through the same `fill()`, and `write()`
    lays the `.dockerignore` with a plain `write_text` (0644), so the second half needs
    the refusal as much as the first. Named by its own path: a pair is not one file."""
    folder = templates(tmp_path)
    (folder / "dockerignore.tmpl").write_text(
        "*\n!src/core\n# root pw {{DB_PASSWORD}}\n", encoding="utf-8", newline="\n"
    )
    with pytest.raises(
        dockerfile.DockerfileError, match=r"DB_PASSWORD.*dockerignore\.tmpl"
    ) as caught:
        dockerfile.render(folder, {**TOKENS, "DB_PASSWORD": SECRET})
    assert "docker history" in str(caught.value)
    assert "Dockerfile.tmpl" not in str(caught.value), "the half that was fine is not accused"
    assert SECRET not in str(caught.value)


def test_render_never_hands_the_secret_to_the_substitution(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Belt to the refusal's braces, as `generate()` does it: the key is dropped from the
    mapping `fill()` sees, so a template that spelled the token would fail as UNFILLED
    even with the refusal gone. Asserted at the seam, because with the refusal in place
    there is no rendered text that could show the difference.
    """
    seen: list[dict[str, str]] = []
    real = composegen.fill

    def spy(text: str, tokens: Mapping[str, str]) -> str:
        seen.append(dict(tokens))
        return real(text, tokens)

    monkeypatch.setattr(composegen, "fill", spy)
    text, ignore = dockerfile.render(templates(tmp_path), {**TOKENS, "DB_PASSWORD": SECRET})
    assert len(seen) == 2, "one call per template half"
    for tokens in seen:
        assert "DB_PASSWORD" not in tokens
        assert tokens["CORE_DIR"] == "/opt/mangos", "the rest of the mapping is untouched"
    assert SECRET not in text and SECRET not in ignore


@dataclass(frozen=True)
class _TwoSecrets:
    """A stand-in secret declaration with two fields, for the derivation rule alone."""

    db_password: str
    soap_password: str


def test_the_refused_tokens_are_derived_from_the_secret_declarations_fields() -> None:
    """`SECRET_TOKENS` is `secret_tokens(native.Secrets)`, not a list somebody maintains.

    Two links, one assertion each. The synthetic type shows the RULE generalises past the
    single field `Secrets` happens to declare today — one token per field, the field name
    upper-cased — which a set built from one real field could never show. The equality
    shows the shipped constant is that function applied to the real declaration: written
    out as a literal instead, it survives untouched while `native.Secrets` grows a second
    field, and that combination is exactly the mutation that found the one-name version
    (added `soap_password` to `Secrets`; the whole suite stayed green).
    """
    assert dockerfile.secret_tokens(_TwoSecrets) == {"DB_PASSWORD", "SOAP_PASSWORD"}
    assert dockerfile.SECRET_TOKENS == dockerfile.secret_tokens(native.Secrets)
    assert "DB_PASSWORD" in dockerfile.SECRET_TOKENS, "today's declaration, refused"


@pytest.mark.parametrize("token", sorted(dockerfile.SECRET_TOKENS))
def test_every_token_the_secret_declaration_produces_is_refused_in_a_template(
    token: str, tmp_path: Path
) -> None:
    """One case per field of `native.Secrets`, generated from the declaration itself.

    A secret added there brings its own case here with nothing to remember, which is what
    deriving the set buys. The parametrize list IS the current answer, so this docstring
    does not restate it; the test below is what shows the machinery carries a second one.

    NOT the guard against an empty `SECRET_TOKENS`. Measured 2026-09-01 by mutating
    `secret_tokens()` to `return frozenset()`: pytest's default for an empty parameter set
    is SKIP, so this test silently vanishes rather than failing. What caught that mutant
    was the sibling assertion `"DB_PASSWORD" in dockerfile.SECRET_TOKENS` in the test
    above. A parametrized test cannot guard the non-emptiness of its own parameters.
    """
    folder = templates(tmp_path)
    (folder / "Dockerfile.tmpl").write_text(
        "FROM debian:12\nENV X={{" + token + "}}\n", encoding="utf-8", newline="\n"
    )
    with pytest.raises(dockerfile.DockerfileError, match=token) as caught:
        dockerfile.render(folder, {**TOKENS, token: SECRET})
    assert "docker history" in str(caught.value)
    assert SECRET not in str(caught.value)


def test_render_refuses_a_template_naming_a_second_declared_secret_not_just_the_password(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Whatever `SECRET_TOKENS` holds is refused — the defeat that made the set a set.

    Measured on the unfixed code (b8973c52), where the refusal was one hard-coded name:
    a template spelling `{{SOAP_PASSWORD}}`, with that key in the mapping the caller hands
    over whole, rendered `ENV SOAP_PASSWORD=tbc-0123456789abcdef` into the Dockerfile and
    the whole suite stayed green.

    The SET is patched rather than `native.Secrets` because the declaration is read once,
    at import; the derivation from the declaration is the test above, and this is the
    other link. One rule violated: the template spells a refused token. The key is in the
    mapping, so `fill()` would have been perfectly happy with it.
    """
    monkeypatch.setattr(dockerfile, "SECRET_TOKENS", frozenset({"DB_PASSWORD", "SOAP_PASSWORD"}))
    folder = templates(tmp_path)
    (folder / "Dockerfile.tmpl").write_text(
        "FROM debian:12\nENV SOAP_PASSWORD={{SOAP_PASSWORD}}\n", encoding="utf-8", newline="\n"
    )
    with pytest.raises(
        dockerfile.DockerfileError, match=r"SOAP_PASSWORD.*Dockerfile\.tmpl"
    ) as caught:
        dockerfile.render(folder, {**TOKENS, "SOAP_PASSWORD": SECRET})
    assert "docker history" in str(caught.value), "the refusal's own words, not fill()'s"
    assert SECRET not in str(caught.value), "a refusal about a secret does not print it"


def test_render_drops_every_refused_token_from_the_mapping_it_fills_with(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The belt covers the whole set, not the first entry: neither key reaches `fill()`.

    Same seam as the single-key test above, over two tokens, because a belt written as one
    `!=` comparison passes that one and lets everything else through.
    """
    monkeypatch.setattr(dockerfile, "SECRET_TOKENS", frozenset({"DB_PASSWORD", "SOAP_PASSWORD"}))
    seen: list[dict[str, str]] = []
    real = composegen.fill

    def spy(text: str, tokens: Mapping[str, str]) -> str:
        seen.append(dict(tokens))
        return real(text, tokens)

    monkeypatch.setattr(composegen, "fill", spy)
    secrets = {"DB_PASSWORD": SECRET, "SOAP_PASSWORD": "tbc-fedcba9876543210"}
    text, ignore = dockerfile.render(templates(tmp_path), {**TOKENS, **secrets})
    assert len(seen) == 2, "one call per template half"
    for tokens in seen:
        assert not (secrets.keys() & tokens.keys()), "no refused key reaches the substitution"
        assert tokens["CORE_DIR"] == "/opt/mangos", "the rest of the mapping is untouched"
    for value in secrets.values():
        assert value not in text and value not in ignore


def test_a_spaced_placeholder_is_refused_as_unfilled_and_not_by_the_secret_rule(
    tmp_path: Path,
) -> None:
    """`{{ DB_PASSWORD }}` is refused too — by `fill()`, and the message has to say so.

    `composegen.fill()` substitutes by literal `out.replace("{{" + key + "}}", value)`,
    so the spaced spelling is never matched at all, with or without the key in the
    mapping. A `{{` therefore survives and `fill()` raises "not a closed placeholder". The
    by-name refusal never sees it either, for the same reason: it looks for the exact
    `{{DB_PASSWORD}}`.

    WITHDRAWN, from the docstring this replaces: "the belt is what does it ... a change to
    the belt would turn this near-miss into a rendered password silently". Both sentences
    were false, and were disproved by mutation on 2026-09-01: with the belt removed
    (`safe = dict(tokens)`) this test PASSED, while
    `test_render_never_hands_the_secret_to_the_substitution` and
    `test_render_drops_every_refused_token_from_the_mapping_it_fills_with` failed. Those
    two guard the belt; this one never did. A test's stated reason for existing is not
    checked by running it, which is how a false one got past review here.

    What it does pin, and the reason to keep it: WHICH rule fired, "unfilled" and "not a
    closed", and NOT "docker history". A near-miss reported as a secret violation would
    send the next reader to the wrong guard.
    """
    folder = templates(tmp_path)
    (folder / "Dockerfile.tmpl").write_text(
        "FROM debian:12\nENV PW={{ DB_PASSWORD }}\n", encoding="utf-8", newline="\n"
    )
    with pytest.raises(dockerfile.DockerfileError, match="not a closed") as caught:
        dockerfile.render(folder, {**TOKENS, "DB_PASSWORD": SECRET})
    said = str(caught.value)
    assert "unfilled" in said, "fill()'s rule fired, not the by-name refusal's"
    assert "docker history" not in said
    assert SECRET not in said


def test_render_names_a_missing_template(tmp_path: Path) -> None:
    with pytest.raises(dockerfile.DockerfileError, match="Dockerfile.tmpl"):
        dockerfile.render(tmp_path, TOKENS)


def test_render_names_the_missing_ignore_template_and_not_the_dockerfile(tmp_path: Path) -> None:
    """Both halves are named by their own path; a pair is not one file."""
    folder = templates(tmp_path)
    (folder / "dockerignore.tmpl").unlink()
    with pytest.raises(dockerfile.DockerfileError, match="dockerignore.tmpl") as caught:
        dockerfile.render(folder, TOKENS)
    assert "Dockerfile.tmpl" not in str(caught.value)


# -- write: ours --------------------------------------------------------------


def test_write_lays_both_files_and_a_second_identical_write_touches_nothing(
    tmp_path: Path,
) -> None:
    text, ignore = dockerfile.render(templates(tmp_path), TOKENS)
    server = server_dir(tmp_path)
    written = dockerfile.write(server, text, ignore)
    assert written == (server / "Dockerfile", server / ".dockerignore")
    assert (server / "Dockerfile").read_text(encoding="utf-8") == text
    assert (server / ".dockerignore").read_text(encoding="utf-8") == ignore
    assert dockerfile.write(server, text, ignore) == ()


def test_write_lays_both_files_with_lf_endings(tmp_path: Path) -> None:
    """`newline="\\n"`, not the platform default.

    On Windows a text write translates `\\n` to `\\r\\n` unless it is told not to, and a
    CRLF Dockerfile is a portability bug the tests above would never see: every string
    comparison in this file goes through `read_text()`, which translates it back.
    """
    text, ignore = dockerfile.render(templates(tmp_path), TOKENS)
    server = server_dir(tmp_path)
    dockerfile.write(server, text, ignore)
    assert b"\r" not in (server / "Dockerfile").read_bytes()
    assert b"\r" not in (server / ".dockerignore").read_bytes()
    assert (server / "Dockerfile").read_bytes() == text.encode("utf-8")


def test_write_rewrites_a_marked_file_whose_text_changed(tmp_path: Path) -> None:
    text, ignore = dockerfile.render(templates(tmp_path), TOKENS)
    server = server_dir(tmp_path)
    dockerfile.write(server, text, ignore)
    newer, _ = dockerfile.render(templates(tmp_path / "v2"), {**TOKENS, "MAKE_JOBS": "4"})
    assert dockerfile.write(server, newer, ignore) == (server / "Dockerfile",)
    assert "make -j4" in (server / "Dockerfile").read_text(encoding="utf-8")


def test_write_rewrites_a_marked_file_that_is_byte_for_byte_crlf(tmp_path: Path) -> None:
    """Unchanged is a BYTE comparison, so a CRLF copy of our own text is rewritten.

    Reading the file back through `read_text()` would translate `\\r\\n` to `\\n` and call
    it identical, and the skip would then preserve a CRLF Dockerfile forever — which is
    exactly the state a `git add` / `git checkout` round-trip of a generated file, or an
    editor with the wrong default, leaves behind.
    """
    text, ignore = dockerfile.render(templates(tmp_path), TOKENS)
    server = server_dir(tmp_path)
    (server / "Dockerfile").write_bytes(text.replace("\n", "\r\n").encode())
    assert dockerfile.write(server, text, ignore) == (
        server / "Dockerfile",
        server / ".dockerignore",
    )
    assert b"\r" not in (server / "Dockerfile").read_bytes()


def test_write_reads_each_file_once_so_a_flaky_read_cannot_accuse_the_user(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """One read answers both questions — may we write, and is the text already right.

    Asking twice (`is_ours()` opens the file, then the equality check opens it again) is
    how a transient read failure turns into "that file was not written by Yu'lon", an
    accusation about the user's folder that the first read had already disproved. The
    file here is readable exactly once.
    """
    text, ignore = dockerfile.render(templates(tmp_path), TOKENS)
    server = server_dir(tmp_path)
    dockerfile.write(server, text, ignore)
    newer, _ = dockerfile.render(templates(tmp_path / "v2"), {**TOKENS, "MAKE_JOBS": "4"})

    real_open = Path.open
    reads: dict[str, int] = {}

    def counting_open(self: Path, mode: str = "r", *args: object, **kwargs: object) -> object:
        if self.parent == server and "w" not in mode:
            reads[self.name] = reads.get(self.name, 0) + 1
            if reads[self.name] > 1:
                raise PermissionError(13, f"{self.name} was read twice")
        return real_open(self, mode, *args, **kwargs)  # type: ignore[arg-type]

    monkeypatch.setattr(Path, "open", counting_open)
    assert dockerfile.write(server, newer, ignore) == (server / "Dockerfile",)
    assert reads == {"Dockerfile": 1, ".dockerignore": 1}


@pytest.mark.parametrize("entry", CMANGOS_ENTRIES, ids=lambda e: e.id)
def test_a_shipped_pair_renders_and_writes_end_to_end(entry: CatalogEntry, tmp_path: Path) -> None:
    """The real thing: catalog tokens, shipped templates, a fresh server dir."""
    text, ignore = dockerfile.render(shipped(entry), composegen.entry_tokens(entry))
    server = server_dir(tmp_path)
    assert dockerfile.write(server, text, ignore) == (
        server / "Dockerfile",
        server / ".dockerignore",
    )
    written = (server / "Dockerfile").read_bytes()
    assert b"\r" not in written
    assert written.startswith(composegen.GENERATED_MARKER.encode("utf-8"))
    assert dockerfile.write(server, text, ignore) == ()


# -- write: theirs ------------------------------------------------------------


def test_write_refuses_a_dockerfile_it_did_not_write(tmp_path: Path) -> None:
    text, ignore = dockerfile.render(templates(tmp_path), TOKENS)
    server = server_dir(tmp_path)
    (server / "Dockerfile").write_text("FROM somebody-elses:image\n", encoding="utf-8")
    with pytest.raises(dockerfile.DockerfileError, match="not written by Yu'lon") as caught:
        dockerfile.write(server, text, ignore)
    assert "could not be read" not in str(caught.value)
    assert (server / "Dockerfile").read_text(encoding="utf-8") == "FROM somebody-elses:image\n"
    assert not (server / ".dockerignore").exists()


def test_a_foreign_dockerignore_stops_the_dockerfile_from_being_written(tmp_path: Path) -> None:
    """Both files are judged before either is written, so a refusal leaves nothing behind.

    Writing the Dockerfile and then refusing on `.dockerignore` would leave a half-built
    build context — and the retry after the user moves the file aside would find the
    Dockerfile already there and skip it, so the pair could never be proved consistent.
    """
    text, ignore = dockerfile.render(templates(tmp_path), TOKENS)
    server = server_dir(tmp_path)
    (server / ".dockerignore").write_text("node_modules\n", encoding="utf-8")
    with pytest.raises(dockerfile.DockerfileError, match=r"\.dockerignore"):
        dockerfile.write(server, text, ignore)
    assert not (server / "Dockerfile").exists()
    assert (server / ".dockerignore").read_text(encoding="utf-8") == "node_modules\n"


def test_a_marker_below_the_first_line_does_not_make_a_file_ours(tmp_path: Path) -> None:
    """First line only, exactly as `composegen.is_ours()` reads it.

    A user who copied our banner into the middle of their own Dockerfile — or a file that
    merely quotes it — has not handed the engine permission to delete it. The first line
    is the one place a marker cannot arrive by accident.
    """
    text, ignore = dockerfile.render(templates(tmp_path), TOKENS)
    server = server_dir(tmp_path)
    theirs = f"FROM somebody-elses:image\n# copied from {composegen.GENERATED_MARKER}\n"
    (server / "Dockerfile").write_text(theirs, encoding="utf-8")
    with pytest.raises(dockerfile.DockerfileError, match="not written by Yu'lon"):
        dockerfile.write(server, text, ignore)
    assert (server / "Dockerfile").read_text(encoding="utf-8") == theirs


def test_the_marker_is_composegens_and_not_a_second_spelling(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """One mechanism: change `composegen.GENERATED_MARKER` and this module changes with it.

    A copy of the marker string here would drift from the compose files' copy, and the
    first symptom would be a Dockerfile this engine refuses to rewrite in a folder it
    installed itself.
    """
    server = server_dir(tmp_path)
    (server / "Dockerfile").write_text(
        f"{composegen.GENERATED_MARKER}\nFROM debian:12\n", encoding="utf-8"
    )
    monkeypatch.setattr(composegen, "GENERATED_MARKER", "# written by something else")
    text, ignore = dockerfile.render(templates(tmp_path), TOKENS)
    with pytest.raises(dockerfile.DockerfileError, match="not written by Yu'lon"):
        dockerfile.write(server, text, ignore)


# -- write: could not tell ----------------------------------------------------


def test_write_says_it_could_not_tell_when_the_file_cannot_be_read(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The third answer. An unreadable file is not evidence of anything.

    `composegen.is_ours()` folds this into False, which reads back to the user as "that
    file was not written by Yu'lon ... point the install at an empty folder" — a claim
    about a file nobody could open, and the wrong remedy for a permission problem.
    """
    text, ignore = dockerfile.render(templates(tmp_path), TOKENS)
    server = server_dir(tmp_path)
    (server / "Dockerfile").write_text(
        f"{composegen.GENERATED_MARKER}\nFROM debian:12\n", encoding="utf-8"
    )
    real_open = Path.open

    def refusing_open(self: Path, mode: str = "r", *args: object, **kwargs: object) -> object:
        if self.name == "Dockerfile" and "w" not in mode:
            raise PermissionError(13, "Permission denied")
        return real_open(self, mode, *args, **kwargs)  # type: ignore[arg-type]

    monkeypatch.setattr(Path, "open", refusing_open)
    with pytest.raises(dockerfile.DockerfileError, match="could not be read") as caught:
        dockerfile.write(server, text, ignore)
    message = str(caught.value)
    assert "not written by Yu'lon" not in message, "this is not an accusation"
    assert "Permission denied" in message, "say what the OS said, or it cannot be fixed"
    assert not (server / ".dockerignore").exists()


def test_write_says_it_could_not_tell_when_a_directory_is_in_the_way(tmp_path: Path) -> None:
    """A real OS error, unpatched: a folder named `Dockerfile` opens on no platform."""
    text, ignore = dockerfile.render(templates(tmp_path), TOKENS)
    server = server_dir(tmp_path)
    (server / "Dockerfile").mkdir()
    with pytest.raises(dockerfile.DockerfileError, match="could not be read") as caught:
        dockerfile.write(server, text, ignore)
    assert "not written by Yu'lon" not in str(caught.value)
    assert (server / "Dockerfile").is_dir()


# -- write: the text handed in ------------------------------------------------


def test_write_refuses_text_that_carries_no_marker(tmp_path: Path) -> None:
    """The `.dockerignore` half is `render()`'s own, so the Dockerfile's missing marker is
    the one thing wrong with this pair. Unmarked text is unrendered text as well — nothing
    `render()` returns lacks the marker — and the marker check runs FIRST so this failure
    is reported as the missing marker rather than as unknown provenance."""
    _, ignore = dockerfile.render(templates(tmp_path), TOKENS)
    server = server_dir(tmp_path)
    with pytest.raises(dockerfile.DockerfileError, match="marker") as caught:
        dockerfile.write(server, "FROM x\n", ignore)
    assert "did not come from" not in str(caught.value)
    assert not (server / "Dockerfile").exists()


def test_write_refuses_ignore_text_that_carries_no_marker(tmp_path: Path) -> None:
    """The `.dockerignore` half is guarded too, and by its own name.

    An unmarked `.dockerignore` written once is a file this engine can never rewrite:
    the next install would refuse the whole folder as somebody else's. The Dockerfile half
    is `render()`'s own so that the ignore half is the only thing wrong here.
    """
    text, _ = dockerfile.render(templates(tmp_path), TOKENS)
    server = server_dir(tmp_path)
    with pytest.raises(dockerfile.DockerfileError, match=r"\.dockerignore") as caught:
        dockerfile.write(server, text, "*\n")
    assert "marker" in str(caught.value)
    assert not (server / "Dockerfile").exists() and not (server / ".dockerignore").exists()


def test_write_refuses_marked_text_that_did_not_come_from_render(tmp_path: Path) -> None:
    """The D4 defeat: `write()` is a public entry point and it used to trust its caller.

    Measured on the unfixed code (b8973c52): `write()` was handed marked text reading
    `ENV PW=tbc-0123456789abcdef`, wrote both files, and the password sat in the build
    context — it validated the marker it generates itself and nothing about the content.
    It cannot recognise the value (the secrets live in `native.Secrets`, which never
    reaches this signature), so what it requires instead is `render()`'s own output, which
    inherits `render()`'s refusal whole.

    One rule violated: the text is not rendered. It carries the marker, and the folder is
    empty, so neither of the other two refusals has anything to say about it.
    """
    _, ignore = dockerfile.render(templates(tmp_path), TOKENS)
    server = server_dir(tmp_path)
    poisoned = f"{composegen.GENERATED_MARKER}\nFROM debian:12\nENV PW={SECRET}\n"
    with pytest.raises(dockerfile.DockerfileError, match="did not come from") as caught:
        dockerfile.write(server, poisoned, ignore)
    assert "render()" in str(caught.value), "and the sentence says what to do instead"
    assert list(server.iterdir()) == [], "nothing written on a refusal"


def test_write_refuses_rendered_text_that_was_edited_after_it_was_rendered(
    tmp_path: Path,
) -> None:
    """A string operation on rendered text yields a plain `str`, and that is the intent.

    Text edited after the render is not the text `render()` checked, so the guarantee
    `write()` inherits no longer covers it. The edit here is innocent; the point is that
    the seam does not care, because it cannot tell an innocent edit from a pasted secret.
    """
    text, ignore = dockerfile.render(templates(tmp_path), TOKENS)
    server = server_dir(tmp_path)
    with pytest.raises(dockerfile.DockerfileError, match="did not come from"):
        dockerfile.write(server, text.replace("debian:12", "debian:13"), ignore)
    assert list(server.iterdir()) == []


def test_write_names_the_file_it_could_not_lay_down(tmp_path: Path) -> None:
    """A write that fails (no folder, full disk) is this module's error, not a traceback."""
    text, ignore = dockerfile.render(templates(tmp_path), TOKENS)
    missing = tmp_path / "nowhere"
    with pytest.raises(dockerfile.DockerfileError, match="could not be written") as caught:
        dockerfile.write(missing, text, ignore)
    assert str(missing / "Dockerfile") in str(caught.value)
